# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time
import warnings

import language_tool_python
import lmproof
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QColor
from deep_translator import GoogleTranslator
from functools import cache


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(403, 452)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 10, 361, 301))
        self.listWidget.setWordWrap(False)
        self.listWidget.setObjectName("listWidget")
        self.input = QtWidgets.QLineEdit(Form)
        self.input.setGeometry(QtCore.QRect(20, 340, 361, 31))
        self.input.setMaxLength(200)
        self.input.setObjectName("input")
        self.input.setPlaceholderText("Enter here message.")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(16, 400, 371, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send = QtWidgets.QPushButton(self.widget)
        self.send.setObjectName("send")
        self.horizontalLayout.addWidget(self.send)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.send.setText(_translate("Form", "Send"))
        self.pushButton.setText(_translate("Form", "Translate"))
        self.send.clicked.connect(lambda: self.translate_message())
        self.send.clicked.connect(lambda: self.check())
        self.pushButton.clicked.connect(lambda: self.translate())
        self.listWidget.setStyleSheet("background-color: #fffdd0;")

    def send_message(self):
        message = self.input.text()
        if message != "":
            nick = "User: "
            showed = nick + message
            self.listWidget.addItem(showed)
            self.listWidget.setStyleSheet("background-color: red")

            return message

    def translate_message(self):
        to_translate = self.send_message()
        translated = "Translated: " + GoogleTranslator(source='auto', target='tr').translate(to_translate)
        self.listWidget.addItem(translated)
        self.listWidget.setStyleSheet("background-color: yellow")

    def translate(self):
        if self.input.text() != "":
            to_translate = self.input.text()
            translated = "Translated: " + GoogleTranslator(source='auto', target="tr").translate(to_translate)
            self.listWidget.item(translated)
            self.listWidget.setStyleSheet("background-color: blue")


    def check(self):
        tool = language_tool_python.LanguageTool('en-US')
        text = self.input.text()
        corrected = tool.correct(text)
        message = "Correct: " + str(corrected)
        self.listWidget.addItem(message)
        self.input.clear()
        self.listWidget.setStyleSheet("background-color: red")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_Form()
    w = QtWidgets.QMainWindow()
    ex.setupUi(w)
    w.show()
    sys.exit(app.exec_())